# fly.toml app configuration file generated for server-crimson-fog-3188 on 2025-08-24T01:07:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-crimson-fog-3188'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false  
  auto_start_machines = true
  min_machines_running = 2 
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
